name: Deploy - Rails Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: []  # <-- CI runs in separate file

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Deploying Rails application..."

            cd /home/pajri_url-shortener/project/url_shortener

            echo "assigning environment variables"
            export RAILS_ENV=production
            export DB_USERNAME=${{ secrets.DB_USERNAME }}
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export DB_HOST=${{ secrets.DB_HOST }}
            export DB_NAME=${{ secrets.DB_NAME }}

            echo "DB_USERNAME=${DB_USERNAME:-not set}"
            echo "DB_HOST=${DB_HOST:-not set}"
            echo "DB_NAME=${DB_NAME:-not set}"

            echo "Fetching latest code..."
            git fetch --all
            git reset --hard origin/main

            echo "Configuring Bundler to skip development and test groups..."
            /home/pajri_url-shortener/.rbenv/shims/bundle config set without 'development test'

            echo "Installing gems..."
            /home/pajri_url-shortener/.rbenv/shims/bundle install

            echo "Precompiling assets..."
            /home/pajri_url-shortener/.rbenv/shims/bundle exec rake assets:precompile
            
            echo "Running migrations..."
            /home/pajri_url-shortener/.rbenv/shims/bundle exec rake db:migrate

            echo "Restarting Puma service..."
            sudo systemctl restart puma

            echo "Deployment completed!"
